# Generated by Django 5.1 on 2024-10-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_table',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_table',
            name='email',
            field=models.CharField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
