# Generated by Django 5.1 on 2024-08-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0002_alter_user_table_email_alter_user_table_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
