# Generated by Django 5.1 on 2024-10-03 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0002_book_table_description_user_table_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='favorites_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_app.book_table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_app.user_table')),
            ],
        ),
    ]
