# Generated by Django 5.1 on 2024-08-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0003_alter_user_table_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='username',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
