# Generated by Django 5.1 on 2024-10-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0004_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='ctype',
            field=models.CharField(default='text', max_length=25),
            preserve_default=False,
        ),
    ]
