# Generated by Django 5.1 on 2024-08-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0004_user_table_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_table',
            name='username',
        ),
    ]
