# Generated by Django 5.1 on 2024-10-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0005_chat_ctype'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='status',
            field=models.CharField(default='viewed', max_length=25),
            preserve_default=False,
        ),
    ]
