# Generated by Django 5.1 on 2024-10-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0006_chat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_table',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
