# Generated by Django 5.1 on 2024-09-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0006_category_table_alter_login_table_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
