# Generated by Django 5.1 on 2024-09-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0007_alter_user_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='username',
            field=models.CharField(default=1, max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_table',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user_table',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
