# Generated by Django 5.1 on 2024-10-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0009_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='NStatus',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
