# Generated by Django 5.1 on 2024-09-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0010_book_table_language_book_table_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_table',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user_table',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
