# Generated by Django 5.1 on 2024-10-30 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0013_feedback_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_blocked', models.BooleanField(default=False)),
                ('LOGIN', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='My_app.login_table')),
            ],
        ),
    ]
