# Generated by Django 5.1 on 2024-10-30 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0014_blockstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockStatus',
        ),
    ]
