# Generated by Django 5.1 on 2024-10-30 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0015_delete_blockstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Active', max_length=10)),
                ('LOGIN', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='My_app.login_table')),
            ],
        ),
    ]
