# Generated by Django 5.1 on 2024-10-31 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_app', '0016_blockstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_text', models.TextField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_app.book_table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='My_app.user_table')),
            ],
        ),
    ]
